version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: bundler
    directory: /gems/foo/
    schedule:
      interval: monthly
